---
- name: Add SSH key to remote server
  hosts: host
  become: yes
  become_method: sudo
  tasks:
    - name: Add SSH public key to authorized_keys
      authorized_key:
        user: ruztem
        key: "{{ lookup('file', '/home/ruztem/.ssh/id_rsa.pub') }}"
        state: present
  tasks:
    - name: Add SSH public key to authorized_keys root
      authorized_key:
        user: root
        key: "{{ lookup('file', '/home/root/.ssh/id_rsa.pub') }}"
        state: present

